const els = {
  pageTitle: document.querySelector("#pageTitle"),
  projectFilter: document.querySelector("#projectFilter"),
  overallProgress: document.querySelector("#overallProgress"),
  progressTrend: document.querySelector("#progressTrend"),
  delayedCount: document.querySelector("#delayedCount"),
  dueSoonCount: document.querySelector("#dueSoonCount"),
  openIssueCount: document.querySelector("#openIssueCount"),
  warningList: document.querySelector("#warningList"),
  taskTable: document.querySelector("#taskTable"),
  taskCount: document.querySelector("#taskCount"),
  taskBuildingSelect: document.querySelector("#taskBuildingSelect"),
  taskSystemSelect: document.querySelector("#taskSystemSelect"),
  excelInput: document.querySelector("#excelInput"),
  importResult: document.querySelector("#importResult"),
  importValidationReport: document.querySelector("#importValidationReport"),
  downloadTemplateBtn: document.querySelector("#downloadTemplateBtn"),
  saveBaselineBtn: document.querySelector("#saveBaselineBtn"),
  exportDelayBtn: document.querySelector("#exportDelayBtn"),
  exportTasksBtn: document.querySelector("#exportTasksBtn"),
  exportBackupBtn: document.querySelector("#exportBackupBtn"),
  backupInput: document.querySelector("#backupInput"),
  importDiffPanel: document.querySelector("#importDiffPanel"),
  importPreviewPanel: document.querySelector("#importPreviewPanel"),
  baselinePanel: document.querySelector("#baselinePanel"),
  restorePointPanel: document.querySelector("#restorePointPanel"),
  taskSearchInput: document.querySelector("#taskSearchInput"),
  taskStatusFilter: document.querySelector("#taskStatusFilter"),
  taskBuildingFilter: document.querySelector("#taskBuildingFilter"),
  taskOwnerFilter: document.querySelector("#taskOwnerFilter"),
  taskSortSelect: document.querySelector("#taskSortSelect"),
  taskFilterResetBtn: document.querySelector("#taskFilterResetBtn"),
  issueBoard: document.querySelector("#issueBoard"),
  issueTaskSelect: document.querySelector("#issueTaskSelect"),
  issueForm: document.querySelector("#issueForm"),
  issueSubmitBtn: document.querySelector("#issueSubmitBtn"),
  cancelIssueEditBtn: document.querySelector("#cancelIssueEditBtn"),
  buildingGrid: document.querySelector("#buildingGrid"),
  buildingModel: document.querySelector("#buildingModel"),
  modelDetail: document.querySelector("#modelDetail"),
  modelSummary: document.querySelector("#modelSummary"),
  modelBuildingFilter: document.querySelector("#modelBuildingFilter"),
  modelUnitFilter: document.querySelector("#modelUnitFilter"),
  modelSystemFilter: document.querySelector("#modelSystemFilter"),
  modelStatusFilter: document.querySelector("#modelStatusFilter"),
  modelAutoRotateBtn: document.querySelector("#modelAutoRotateBtn"),
  modelResetFilterBtn: document.querySelector("#modelResetFilterBtn"),
  modelFloorPanel: document.querySelector("#modelFloorPanel"),
  modelTooltip: document.querySelector("#modelTooltip"),
  disciplineLegend: document.querySelector("#disciplineLegend"),
  scopeUnitGrid: document.querySelector("#scopeUnitGrid"),
  scopeSummary: document.querySelector("#scopeSummary"),
  scopeManageSummary: document.querySelector("#scopeManageSummary"),
  buildingScopeForm: document.querySelector("#buildingScopeForm"),
  unitScopeForm: document.querySelector("#unitScopeForm"),
  saveBuildingScopeBtn: document.querySelector("#saveBuildingScopeBtn"),
  cancelBuildingEditBtn: document.querySelector("#cancelBuildingEditBtn"),
  saveUnitScopeBtn: document.querySelector("#saveUnitScopeBtn"),
  cancelUnitEditBtn: document.querySelector("#cancelUnitEditBtn"),
  scopeMaintenanceList: document.querySelector("#scopeMaintenanceList"),
  taskForm: document.querySelector("#taskForm"),
  taskSubmitBtn: document.querySelector("#taskSubmitBtn"),
  cancelTaskEditBtn: document.querySelector("#cancelTaskEditBtn"),
  deviationSummary: document.querySelector("#deviationSummary"),
  deviationList: document.querySelector("#deviationList"),
  dependencyList: document.querySelector("#dependencyList"),
  unitRanking: document.querySelector("#unitRanking"),
  generateWeeklyBtn: document.querySelector("#generateWeeklyBtn"),
  copyWeeklyBtn: document.querySelector("#copyWeeklyBtn"),
  carouselBtn: document.querySelector("#carouselBtn"),
  carouselExitBtn: document.querySelector("#carouselExitBtn"),
  weeklyReportOutput: document.querySelector("#weeklyReportOutput"),
  weeklySummary: document.querySelector("#weeklySummary"),
  basementSummary: document.querySelector("#basementSummary"),
  basementCutaway: document.querySelector("#basementCutaway"),
  chart: document.querySelector("#progressChart")
};

let modelState = null;
let selectedBuildingName = "";
let selectedModelFloor = "";
let lastImportFocus = null;
let pendingImport = null;
const taskFilters = {
  query: "",
  status: "all",
  building: "all",
  owner: "all",
  sort: "plannedAsc"
};
